### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mzanella** [mzanella/CNSProject#16]
- [x] How many accounts were connected to the social network such as Facebook and Linkedin? You mention that few accounts, but I recommend you must quantify it. 
- [x] What are the most commonly used hashtags?
- [x] Please state the temporal information: like when the dataset was collected, when was the most frequent discussion held etc
- [x] The time (runtime analysis) for attribute extractions and building the knowledge out of it is not presented. Can you state it?
- [x] Can we draw some conclusions out of search techniques used? I meant technique X resulted in Y address etc.
- [x] The figure is not clear to me. However, you have tried explaining the observations in the paragraphs, which I really appreciate.
- [x] What was the procedure employed to eliminate false positive?
- [x] Can we draw a fine-grained diagram of the proposed architecture? Like what is the input to the module, what is the output how are they linked etc?
